/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "gamedata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PInputState, PInputState, AUTO)


PB_BIND(PInputState_Vector2, PInputState_Vector2, AUTO)


PB_BIND(PEntityState, PEntityState, AUTO)


PB_BIND(PEntityState_Vector3, PEntityState_Vector3, AUTO)


PB_BIND(EntityStateBatch, EntityStateBatch, 2)


PB_BIND(GameMessage, GameMessage, 2)



