/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SensorReading_Status {
    SensorReading_Status_UNKNOWN = 0,
    SensorReading_Status_OK = 1,
    SensorReading_Status_WARNING = 2,
    SensorReading_Status_ERROR = 3
} SensorReading_Status;

/* Struct definitions */
typedef struct _SensorReading {
    char sensor_id[24];
    uint64_t timestamp;
    float value;
    SensorReading_Status status;
} SensorReading;

typedef struct _SensorBatch {
    pb_size_t readings_count;
    SensorReading readings[5];
} SensorBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SensorReading_Status_MIN SensorReading_Status_UNKNOWN
#define _SensorReading_Status_MAX SensorReading_Status_ERROR
#define _SensorReading_Status_ARRAYSIZE ((SensorReading_Status)(SensorReading_Status_ERROR+1))

#define SensorReading_status_ENUMTYPE SensorReading_Status



/* Initializer values for message structs */
#define SensorReading_init_default               {"", 0, 0, _SensorReading_Status_MIN}
#define SensorBatch_init_default                 {0, {SensorReading_init_default, SensorReading_init_default, SensorReading_init_default, SensorReading_init_default, SensorReading_init_default}}
#define SensorReading_init_zero                  {"", 0, 0, _SensorReading_Status_MIN}
#define SensorBatch_init_zero                    {0, {SensorReading_init_zero, SensorReading_init_zero, SensorReading_init_zero, SensorReading_init_zero, SensorReading_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SensorReading_sensor_id_tag              1
#define SensorReading_timestamp_tag              2
#define SensorReading_value_tag                  3
#define SensorReading_status_tag                 4
#define SensorBatch_readings_tag                 1

/* Struct field encoding specification for nanopb */
#define SensorReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4)
#define SensorReading_CALLBACK NULL
#define SensorReading_DEFAULT NULL

#define SensorBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  readings,          1)
#define SensorBatch_CALLBACK NULL
#define SensorBatch_DEFAULT NULL
#define SensorBatch_readings_MSGTYPE SensorReading

extern const pb_msgdesc_t SensorReading_msg;
extern const pb_msgdesc_t SensorBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorReading_fields &SensorReading_msg
#define SensorBatch_fields &SensorBatch_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_PB_H_MAX_SIZE                     SensorBatch_size
#define SensorBatch_size                         225
#define SensorReading_size                       43

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
