// gamedata.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gamedata.proto

// 这是为 Go 语言添加的选项

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -------------------
//
//	InputState
//
// -------------------
type PInputState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// 【优化点 1】: 将 repeated 字段改为固定大小的数组。
	// 这需要在 .options 文件中配合 max_count:4 使用。
	// 这避免了使用复杂的 pb_callback_t，可以直接进行数组拷贝。
	WasdPressed    []uint32             `protobuf:"varint,2,rep,packed,name=wasd_pressed,json=wasdPressed,proto3" json:"wasd_pressed,omitempty"`
	SpacePressed   uint32               `protobuf:"varint,3,opt,name=space_pressed,json=spacePressed,proto3" json:"space_pressed,omitempty"`
	MouseDelta     *PInputState_Vector2 `protobuf:"bytes,4,opt,name=mouseDelta,proto3" json:"mouseDelta,omitempty"`
	SequenceNumber uint32               `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PInputState) Reset() {
	*x = PInputState{}
	mi := &file_proto_gamedata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PInputState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PInputState) ProtoMessage() {}

func (x *PInputState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PInputState.ProtoReflect.Descriptor instead.
func (*PInputState) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{0}
}

func (x *PInputState) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PInputState) GetWasdPressed() []uint32 {
	if x != nil {
		return x.WasdPressed
	}
	return nil
}

func (x *PInputState) GetSpacePressed() uint32 {
	if x != nil {
		return x.SpacePressed
	}
	return 0
}

func (x *PInputState) GetMouseDelta() *PInputState_Vector2 {
	if x != nil {
		return x.MouseDelta
	}
	return nil
}

func (x *PInputState) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// -------------------
//
//	EntityState
//
// -------------------
type PEntityState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsError        bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Position       *PEntityState_Vector3  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Forward        *PEntityState_Vector3  `protobuf:"bytes,4,opt,name=forward,proto3" json:"forward,omitempty"`
	Velocity       *PEntityState_Vector3  `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	BoundingBoxMin *PEntityState_Vector3  `protobuf:"bytes,6,opt,name=bounding_box_min,json=boundingBoxMin,proto3" json:"bounding_box_min,omitempty"`
	BoundingBoxMax *PEntityState_Vector3  `protobuf:"bytes,7,opt,name=bounding_box_max,json=boundingBoxMax,proto3" json:"bounding_box_max,omitempty"`
	PosPoint       *PEntityState_Vector3  `protobuf:"bytes,8,opt,name=pos_point,json=posPoint,proto3" json:"pos_point,omitempty"`
	IsPlayer       bool                   `protobuf:"varint,9,opt,name=is_player,json=isPlayer,proto3" json:"is_player,omitempty"`
	SeqNum         uint32                 `protobuf:"varint,10,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Health         uint32                 `protobuf:"varint,11,opt,name=health,proto3" json:"health,omitempty"`
	Weapon         uint32                 `protobuf:"varint,12,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Wasd           []bool                 `protobuf:"varint,13,rep,packed,name=wasd,proto3" json:"wasd,omitempty"`
	Space          bool                   `protobuf:"varint,14,opt,name=space,proto3" json:"space,omitempty"`
	Lastticks      uint32                 `protobuf:"varint,15,opt,name=lastticks,proto3" json:"lastticks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PEntityState) Reset() {
	*x = PEntityState{}
	mi := &file_proto_gamedata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEntityState) ProtoMessage() {}

func (x *PEntityState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEntityState.ProtoReflect.Descriptor instead.
func (*PEntityState) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{1}
}

func (x *PEntityState) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PEntityState) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *PEntityState) GetPosition() *PEntityState_Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PEntityState) GetForward() *PEntityState_Vector3 {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *PEntityState) GetVelocity() *PEntityState_Vector3 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *PEntityState) GetBoundingBoxMin() *PEntityState_Vector3 {
	if x != nil {
		return x.BoundingBoxMin
	}
	return nil
}

func (x *PEntityState) GetBoundingBoxMax() *PEntityState_Vector3 {
	if x != nil {
		return x.BoundingBoxMax
	}
	return nil
}

func (x *PEntityState) GetPosPoint() *PEntityState_Vector3 {
	if x != nil {
		return x.PosPoint
	}
	return nil
}

func (x *PEntityState) GetIsPlayer() bool {
	if x != nil {
		return x.IsPlayer
	}
	return false
}

func (x *PEntityState) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PEntityState) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PEntityState) GetWeapon() uint32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *PEntityState) GetWasd() []bool {
	if x != nil {
		return x.Wasd
	}
	return nil
}

func (x *PEntityState) GetSpace() bool {
	if x != nil {
		return x.Space
	}
	return false
}

func (x *PEntityState) GetLastticks() uint32 {
	if x != nil {
		return x.Lastticks
	}
	return 0
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_gamedata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Playerid      uint32                 `protobuf:"varint,2,opt,name=playerid,proto3" json:"playerid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_gamedata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServerHello) GetPlayerid() uint32 {
	if x != nil {
		return x.Playerid
	}
	return 0
}

// -------------------
// EntityStateBatch
// -------------------
// 这个消息用于一次性发送多个实体状态，保持不变。
type EntityStateBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityState   []*PEntityState        `protobuf:"bytes,1,rep,name=entity_state,json=entityState,proto3" json:"entity_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityStateBatch) Reset() {
	*x = EntityStateBatch{}
	mi := &file_proto_gamedata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityStateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStateBatch) ProtoMessage() {}

func (x *EntityStateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStateBatch.ProtoReflect.Descriptor instead.
func (*EntityStateBatch) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{4}
}

func (x *EntityStateBatch) GetEntityState() []*PEntityState {
	if x != nil {
		return x.EntityState
	}
	return nil
}

type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessage_InputState
	//	*GameMessage_EntityStateBatch
	//	*GameMessage_Chello
	//	*GameMessage_Shello
	Payload       isGameMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_proto_gamedata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{5}
}

func (x *GameMessage) GetPayload() isGameMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetInputState() *PInputState {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_InputState); ok {
			return x.InputState
		}
	}
	return nil
}

func (x *GameMessage) GetEntityStateBatch() *EntityStateBatch {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_EntityStateBatch); ok {
			return x.EntityStateBatch
		}
	}
	return nil
}

func (x *GameMessage) GetChello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Chello); ok {
			return x.Chello
		}
	}
	return nil
}

func (x *GameMessage) GetShello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Shello); ok {
			return x.Shello
		}
	}
	return nil
}

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_InputState struct {
	InputState *PInputState `protobuf:"bytes,1,opt,name=input_state,json=inputState,proto3,oneof"`
}

type GameMessage_EntityStateBatch struct {
	EntityStateBatch *EntityStateBatch `protobuf:"bytes,2,opt,name=entity_state_batch,json=entityStateBatch,proto3,oneof"`
}

type GameMessage_Chello struct {
	Chello *ClientHello `protobuf:"bytes,3,opt,name=chello,proto3,oneof"`
}

type GameMessage_Shello struct {
	Shello *ServerHello `protobuf:"bytes,4,opt,name=shello,proto3,oneof"`
}

func (*GameMessage_InputState) isGameMessage_Payload() {}

func (*GameMessage_EntityStateBatch) isGameMessage_Payload() {}

func (*GameMessage_Chello) isGameMessage_Payload() {}

func (*GameMessage_Shello) isGameMessage_Payload() {}

// 嵌套的 Vector2 定义保持不变
type PInputState_Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PInputState_Vector2) Reset() {
	*x = PInputState_Vector2{}
	mi := &file_proto_gamedata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PInputState_Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PInputState_Vector2) ProtoMessage() {}

func (x *PInputState_Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PInputState_Vector2.ProtoReflect.Descriptor instead.
func (*PInputState_Vector2) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PInputState_Vector2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PInputState_Vector2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PEntityState_Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEntityState_Vector3) Reset() {
	*x = PEntityState_Vector3{}
	mi := &file_proto_gamedata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEntityState_Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEntityState_Vector3) ProtoMessage() {}

func (x *PEntityState_Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamedata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEntityState_Vector3.ProtoReflect.Descriptor instead.
func (*PEntityState_Vector3) Descriptor() ([]byte, []int) {
	return file_proto_gamedata_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PEntityState_Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PEntityState_Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PEntityState_Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_proto_gamedata_proto protoreflect.FileDescriptor

const file_proto_gamedata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/gamedata.proto\x12\bgamedata\"\x81\x02\n" +
	"\vPInputState\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12!\n" +
	"\fwasd_pressed\x18\x02 \x03(\rR\vwasdPressed\x12#\n" +
	"\rspace_pressed\x18\x03 \x01(\rR\fspacePressed\x12=\n" +
	"\n" +
	"mouseDelta\x18\x04 \x01(\v2\x1d.gamedata.PInputState.Vector2R\n" +
	"mouseDelta\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\rR\x0esequenceNumber\x1a%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\x9f\x05\n" +
	"\fPEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12:\n" +
	"\bposition\x18\x03 \x01(\v2\x1e.gamedata.PEntityState.Vector3R\bposition\x128\n" +
	"\aforward\x18\x04 \x01(\v2\x1e.gamedata.PEntityState.Vector3R\aforward\x12:\n" +
	"\bvelocity\x18\x05 \x01(\v2\x1e.gamedata.PEntityState.Vector3R\bvelocity\x12H\n" +
	"\x10bounding_box_min\x18\x06 \x01(\v2\x1e.gamedata.PEntityState.Vector3R\x0eboundingBoxMin\x12H\n" +
	"\x10bounding_box_max\x18\a \x01(\v2\x1e.gamedata.PEntityState.Vector3R\x0eboundingBoxMax\x12;\n" +
	"\tpos_point\x18\b \x01(\v2\x1e.gamedata.PEntityState.Vector3R\bposPoint\x12\x1b\n" +
	"\tis_player\x18\t \x01(\bR\bisPlayer\x12\x17\n" +
	"\aseq_num\x18\n" +
	" \x01(\rR\x06seqNum\x12\x16\n" +
	"\x06health\x18\v \x01(\rR\x06health\x12\x16\n" +
	"\x06weapon\x18\f \x01(\rR\x06weapon\x12\x12\n" +
	"\x04wasd\x18\r \x03(\bR\x04wasd\x12\x14\n" +
	"\x05space\x18\x0e \x01(\bR\x05space\x12\x1c\n" +
	"\tlastticks\x18\x0f \x01(\rR\tlastticks\x1a3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"!\n" +
	"\vClientHello\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\"=\n" +
	"\vServerHello\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x1a\n" +
	"\bplayerid\x18\x02 \x01(\rR\bplayerid\"M\n" +
	"\x10EntityStateBatch\x129\n" +
	"\fentity_state\x18\x01 \x03(\v2\x16.gamedata.PEntityStateR\ventityState\"\x80\x02\n" +
	"\vGameMessage\x128\n" +
	"\vinput_state\x18\x01 \x01(\v2\x15.gamedata.PInputStateH\x00R\n" +
	"inputState\x12J\n" +
	"\x12entity_state_batch\x18\x02 \x01(\v2\x1a.gamedata.EntityStateBatchH\x00R\x10entityStateBatch\x12/\n" +
	"\x06chello\x18\x03 \x01(\v2\x15.gamedata.ClientHelloH\x00R\x06chello\x12/\n" +
	"\x06shello\x18\x04 \x01(\v2\x15.gamedata.ServerHelloH\x00R\x06shelloB\t\n" +
	"\apayloadB!Z\x1fgithub.com/yourname/quickfps/pbb\x06proto3"

var (
	file_proto_gamedata_proto_rawDescOnce sync.Once
	file_proto_gamedata_proto_rawDescData []byte
)

func file_proto_gamedata_proto_rawDescGZIP() []byte {
	file_proto_gamedata_proto_rawDescOnce.Do(func() {
		file_proto_gamedata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gamedata_proto_rawDesc), len(file_proto_gamedata_proto_rawDesc)))
	})
	return file_proto_gamedata_proto_rawDescData
}

var file_proto_gamedata_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_gamedata_proto_goTypes = []any{
	(*PInputState)(nil),          // 0: gamedata.PInputState
	(*PEntityState)(nil),         // 1: gamedata.PEntityState
	(*ClientHello)(nil),          // 2: gamedata.ClientHello
	(*ServerHello)(nil),          // 3: gamedata.ServerHello
	(*EntityStateBatch)(nil),     // 4: gamedata.EntityStateBatch
	(*GameMessage)(nil),          // 5: gamedata.GameMessage
	(*PInputState_Vector2)(nil),  // 6: gamedata.PInputState.Vector2
	(*PEntityState_Vector3)(nil), // 7: gamedata.PEntityState.Vector3
}
var file_proto_gamedata_proto_depIdxs = []int32{
	6,  // 0: gamedata.PInputState.mouseDelta:type_name -> gamedata.PInputState.Vector2
	7,  // 1: gamedata.PEntityState.position:type_name -> gamedata.PEntityState.Vector3
	7,  // 2: gamedata.PEntityState.forward:type_name -> gamedata.PEntityState.Vector3
	7,  // 3: gamedata.PEntityState.velocity:type_name -> gamedata.PEntityState.Vector3
	7,  // 4: gamedata.PEntityState.bounding_box_min:type_name -> gamedata.PEntityState.Vector3
	7,  // 5: gamedata.PEntityState.bounding_box_max:type_name -> gamedata.PEntityState.Vector3
	7,  // 6: gamedata.PEntityState.pos_point:type_name -> gamedata.PEntityState.Vector3
	1,  // 7: gamedata.EntityStateBatch.entity_state:type_name -> gamedata.PEntityState
	0,  // 8: gamedata.GameMessage.input_state:type_name -> gamedata.PInputState
	4,  // 9: gamedata.GameMessage.entity_state_batch:type_name -> gamedata.EntityStateBatch
	2,  // 10: gamedata.GameMessage.chello:type_name -> gamedata.ClientHello
	3,  // 11: gamedata.GameMessage.shello:type_name -> gamedata.ServerHello
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_gamedata_proto_init() }
func file_proto_gamedata_proto_init() {
	if File_proto_gamedata_proto != nil {
		return
	}
	file_proto_gamedata_proto_msgTypes[5].OneofWrappers = []any{
		(*GameMessage_InputState)(nil),
		(*GameMessage_EntityStateBatch)(nil),
		(*GameMessage_Chello)(nil),
		(*GameMessage_Shello)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gamedata_proto_rawDesc), len(file_proto_gamedata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gamedata_proto_goTypes,
		DependencyIndexes: file_proto_gamedata_proto_depIdxs,
		MessageInfos:      file_proto_gamedata_proto_msgTypes,
	}.Build()
	File_proto_gamedata_proto = out.File
	file_proto_gamedata_proto_goTypes = nil
	file_proto_gamedata_proto_depIdxs = nil
}
